server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hidden-method:
      filter:
        enabled=true: